# Generated by Django 6.0.3 on 2026-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_branch_manager_alter_branch_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='info_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
