# Generated by Django 6.0.3 on 2026-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_admission_consent_given_admission_info_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='district',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
    ]
