# Generated by Django 5.2.6 on 2026-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_branch_city_remove_branch_contact_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
