# Generated by Django 5.2.6 on 2026-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_admission_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, help_text='Full branch address for receipts', null=True),
        ),
    ]
