# Generated by Django 5.2.6 on 2026-04-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_add_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='portal.course'),
        ),
    ]
