# Generated by Django 5.2.6 on 2026-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='counselling_type',
            field=models.CharField(blank=True, help_text='JoSAA / MHT-CET / Both – for Engineering Admission Guidance', max_length=60, null=True),
        ),
    ]
