# Generated by Django 6.0.3 on 2026-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_add_counselling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
