# Generated by Django 5.2.6 on 2026-04-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_admission_application_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCourseCounsellingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_type', models.CharField(choices=[('JoSAA', 'JoSAA'), ('CET', 'MHT-CET'), ('Both', 'Both (JoSAA + CET)')], max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_fees', to='portal.branchcourse')),
            ],
            options={
                'ordering': ['counselling_type'],
                'unique_together': {('branch_course', 'counselling_type')},
            },
        ),
    ]
