# Generated by Django 5.2.6 on 2026-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_add_counselling_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcourse',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
