# Generated by Django 6.0.3 on 2026-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_branch_course_fee_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='jee_application_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='jee_expected_marks',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mht_cet_pcb_application_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mht_cet_pcb_expected_marks',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mht_cet_pcm_application_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mht_cet_pcm_expected_marks',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
