# Generated by Django 5.2.6 on 2026-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_enquiry_course_type_enquiry_jee_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcoursecounsellingfee',
            name='counselling_type',
            field=models.CharField(choices=[('JoSAA', 'JoSAA'), ('CET', 'MHT-CET'), ('Both', 'Both (JoSAA + CET)'), ('MH_Medical', 'MH_Medical'), ('Other_Medical', 'Other_Medical'), ('Combo_Medical', 'Combo_Medical')], max_length=20),
        ),
    ]
